# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-12-28 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amcapp', '0004_auto_20181228_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
